### ISSUE TITLE
increase http timeouts

### ISSUE THREAD

**Issue by kabaluyot** [erply/api-go-wrapper#1]
Im an applicant for erply go dev role, wanted to use this official package for erply api go wrapper, I noticed inconsistent api calls because of the very short timeout (ResponseHeaderTimeout specifically) that is around 3s. Please review if it is best to increase it. If yes, I can send PR. Thanks

**Comment by Dysar** [comment]
Hi, thanks for reaching out! 

Are you using `NewClient` function to create a client? In that case it is possible to pass your own `*http.Client` that will be used to make requests with a custom ResponseHeaderTimeout.

Best, David

**Comment by kabaluyot** [comment]
Yes, ah that custom http client. Also sir, is the new client still maintained? I see a v2 implementation of the client.
