### ISSUE TITLE
Important data is hidden in the internal package

### ISSUE THREAD

**Issue by breathbath** [erply/api-go-wrapper#12]
There is no reason to hide `common.Status` in internal status as well as make e.g. `getSuppliersResponse` not accessible from outside. 
I would never hide any data from the outside caller which is returned in the API response. Imagine the use case when Erply DB contains 100000 products, so it's crucial to know e.g. RecordsTotal value in the Status so the caller can plan the amount of requests, calculate offsets etc. It's not reasonable to decide for user what he needs and what not and don't give chance to fetch any metadata from api.

**Comment by Dysar** [comment]
Hi, good point!

Are you planning to do a PR to return the important data to be accessible from the outside?

**Comment by breathbath** [comment]
https://github.com/erply/api-go-wrapper/pull/13/files

**Comment by breathbath** [comment]
You've closed it without merge?

**Comment by Dysar** [comment]
Yeah, I will let you know when it gets implemented. I saw that you added a return of 2 objects - 1 for status and the other for the result itself - would it be simpler to return just an object in the underlying API response style or you see some benefits that the separation brings?
17 мая 2020 г., 20:46 +0300, Andrey <notifications@github.com>, писал:

You've closed it without merge?

**Comment by Dysar** [comment]
Alright, the change got implemented, closing this one
